version: '2'

services:
  redis:
    image: 'redis'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  web:
    build:
      context: ./chess-web
      dockerfile: Dockerfile
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "chessweb:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    links:
       - manager:chessdocker
    ports:
     - "8000:8000"
    depends_on:
     - redis

  manager:
    build:
      context: ./chess-docker
      dockerfile: Dockerfile
    command: >
      gunicorn -b 0.0.0.0:5001
        --access-logfile -
        --reload
        "chessdocker:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    hostname: chessdocker
    ports:
     - "5001:5001"
    depends_on:
     - redis

  worker:
    build:
      context: ./chess-docker
      dockerfile: Dockerfile
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    command: celery worker -l info -A chessdocker.celery
    depends_on:
      - redis

  ai:
    build:
      context: ./chess-ai
      dockerfile: Dockerfile
    depends_on:
      - redis
      
volumes:
  redis:


